import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fintrack',
  description: 'Generated by create next app',
}

// eslint-disable-next-line react/prop-types
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Sidebar />
    </html>
  )
}
